export const getAbbreviationMapping = (): Map<string, string> => {
  const abbreviationMapping = new Map();

  abbreviationMapping.set('absol.', 'absolute, absolutely.');
  abbreviationMapping.set('acc.', 'accusative.');
  abbreviationMapping.set('act.', 'active.');
  abbreviationMapping.set('A. D.', 'Anno Domini.');
  abbreviationMapping.set('adj.', 'adjective.');
  abbreviationMapping.set('adv.', 'adverb.');
  abbreviationMapping.set('adverb.', 'adverbially.');
  abbreviationMapping.set('allit.', 'alliteration, alliterative.');
  abbreviationMapping.set('natom.', 'anatomically.');
  abbreviationMapping.set('απ. λεγ.', 'απαξ. λεγόμενον.');
  abbreviationMapping.set('A. S.', 'Anglo-Saxon.');
  abbreviationMapping.set('astron.', 'astronomy, astronomically.');
  abbreviationMapping.set('begin.', 'beginning.');
  abbreviationMapping.set('Bodl.', 'Bodleian.');
  abbreviationMapping.set('Bohem.', 'Bohemian.');
  abbreviationMapping.set('botan.', 'botanically.');
  abbreviationMapping.set('Brit. Mus.', 'British Museum.');
  abbreviationMapping.set('ch.', 'chapter.');
  abbreviationMapping.set('class.', 'classical.');
  abbreviationMapping.set('Cod. or Cd.', 'Codex.');
  abbreviationMapping.set('cognom.', 'cognomen.');
  abbreviationMapping.set('collect.', 'collective.');
  abbreviationMapping.set('compar.', 'comparative.');
  abbreviationMapping.set('compd.', 'compound.');
  abbreviationMapping.set('compds.', 'compounds.');
  abbreviationMapping.set('conj.', 'conjunction.');
  abbreviationMapping.set('contr.', 'contracted.');
  abbreviationMapping.set('corresp.', 'corresponding.');
  abbreviationMapping.set('cp.', 'compare.');
  abbreviationMapping.set('Dan.', 'Danish.');
  abbreviationMapping.set('dat.', 'dative.');
  abbreviationMapping.set('decl.', 'declined.');
  abbreviationMapping.set('def.', 'definite.');
  abbreviationMapping.set('defect.', 'defective.');
  abbreviationMapping.set('dep.', 'deponent.');
  abbreviationMapping.set('DeProfesser', 'De Herr Professer by August Corrodi, in the Zürich idiom.');
  abbreviationMapping.set('deriv.', 'derived.');
  abbreviationMapping.set('dict.', 'dictionary.');
  abbreviationMapping.set('dimin.', 'diminutive.');
  abbreviationMapping.set('dissyl.', 'dissyllabic.');
  abbreviationMapping.set('D. R. A.', 'Deutsche Rechts-alterthümer by Grimm.');
  abbreviationMapping.set('dub.', 'dubious.');
  abbreviationMapping.set('eccl.', 'ecclesiastical.');
  abbreviationMapping.set('Ed., Edd.', 'edition, editions, edited.');
  abbreviationMapping.set('E. Engl. Spec.', 'Early English Specimens.');
  abbreviationMapping.set('e. g.', 'exempli gratia.');
  abbreviationMapping.set('ellipt.', 'elliptical, elliptically.');
  abbreviationMapping.set('Engl.', 'English.');
  abbreviationMapping.set('esp.', 'especially.');
  abbreviationMapping.set('etc.', 'et cetera.');
  abbreviationMapping.set('etym.', 'etymology.');
  abbreviationMapping.set('f.', 'feminine.');
  abbreviationMapping.set('fem.', 'feminine.');
  abbreviationMapping.set('Fin.', 'Finnish.');
  abbreviationMapping.set('for.', 'foreign.');
  abbreviationMapping.set('Fr.', 'French in etymologies.');
  abbreviationMapping.set('Frank.', 'Frankish.');
  abbreviationMapping.set('freq.', 'frequent, frequently.');
  abbreviationMapping.set('Fris.', 'Frisian.');
  abbreviationMapping.set('Gael.', 'Gaelic.');
  abbreviationMapping.set('gen.', 'genitive.');
  abbreviationMapping.set('gener.', 'generally.');
  abbreviationMapping.set('Germ.', 'German.');
  abbreviationMapping.set('gl.', 'glossary.');
  abbreviationMapping.set('gloss.', 'glossary.');
  abbreviationMapping.set('Goth.', 'Gothic.');
  abbreviationMapping.set('Gr.', 'Greek.');
  abbreviationMapping.set('gramm.', 'grammar.');
  abbreviationMapping.set('Havn.', 'Havniensis.');
  abbreviationMapping.set('Hel.', 'Heliand.');
  abbreviationMapping.set('Icel.', 'Iceland, Icelander, Icelanders, Icelandic.');
  abbreviationMapping.set('id.', 'idem, referring to the passage quoted or to the translation');
  abbreviationMapping.set('i. e.', 'id est.');
  abbreviationMapping.set('imperat.', 'imperative.');
  abbreviationMapping.set('impers.', 'impersonal.');
  abbreviationMapping.set('indecl.', 'indeclinable.');
  abbreviationMapping.set('indef.', 'indefinite.');
  abbreviationMapping.set('indic.', 'indicative.');
  abbreviationMapping.set('infin.', 'infinitive.');
  abbreviationMapping.set('inflex.', 'inflexive.');
  abbreviationMapping.set('intens.', 'intensive.');
  abbreviationMapping.set('intrans.', 'intransitive.');
  abbreviationMapping.set('irreg.', 'irregular.');
  abbreviationMapping.set('Ital.', 'Italian.');
  abbreviationMapping.set('l.', 'line.');
  abbreviationMapping.set('L.', 'Linnæus.');
  abbreviationMapping.set('Lat.', 'Latin.');
  abbreviationMapping.set('l. c.', 'loco citato.');
  abbreviationMapping.set('lit.', 'literally.');
  abbreviationMapping.set('Lith.', 'Lithuanian.');
  abbreviationMapping.set('Litt.', 'Littonian.');
  abbreviationMapping.set('loc.', 'local, locally.');
  abbreviationMapping.set('m.', 'masculine.');
  abbreviationMapping.set('masc.', 'masculine.');
  abbreviationMapping.set('medic.', 'medicine, medically.');
  abbreviationMapping.set('metaph.', 'metaphorical, metaphorically.');
  abbreviationMapping.set('metath.', 'metathesis.');
  abbreviationMapping.set('meton.', 'metonomy, metonomically.');
  abbreviationMapping.set('metric.', 'metrically.');
  abbreviationMapping.set('mid. H. G.', 'middle High German.');
  abbreviationMapping.set('mid. Lat.', 'middle Latin.');
  abbreviationMapping.set('milit.', 'military.');
  abbreviationMapping.set('M. Lat.', 'Mediæval Latin.');
  abbreviationMapping.set('mod.', 'modern.');
  abbreviationMapping.set('monosyl.', 'monosyllabic.');
  abbreviationMapping.set('MS., MSS.', 'manuscript, manuscripts.');
  abbreviationMapping.set('mythol.', 'mythology, mythologically.');
  abbreviationMapping.set('n.', 'neuter.');
  abbreviationMapping.set('neut.', 'neuter.');
  abbreviationMapping.set('naut.', 'nautical.');
  abbreviationMapping.set('navig.', 'navigation.');
  abbreviationMapping.set('neg.', 'negative.');
  abbreviationMapping.set('N. H. G.', 'New High German.');
  abbreviationMapping.set('no.', 'number.');
  abbreviationMapping.set('nom.', 'nominative.');
  abbreviationMapping.set('North. E.', 'Northern English.');
  abbreviationMapping.set('Norweg.', 'Norwegian.');
  abbreviationMapping.set('obsol.', 'obsolete.');
  abbreviationMapping.set('O. H. G.', 'Old High German.');
  abbreviationMapping.set('opp.', 'opposed.');
  abbreviationMapping.set('Ormul.', 'Ormulum.');
  abbreviationMapping.set('Orm.', 'Ormulum.');
  abbreviationMapping.set('part.', 'participle.');
  abbreviationMapping.set('partic.', 'particularly.');
  abbreviationMapping.set('pass.', 'passive.');
  abbreviationMapping.set('perh.', 'perhaps.');
  abbreviationMapping.set('pers.', 'person.');
  abbreviationMapping.set('pl.', 'plural.');
  abbreviationMapping.set('plur.', 'plural.');
  abbreviationMapping.set('poët.', 'poetically.');
  abbreviationMapping.set('Pol.', 'Polish.');
  abbreviationMapping.set('posit.', 'positive.');
  abbreviationMapping.set('pr.', 'proper, properly.');
  abbreviationMapping.set('prop.', 'proper, properly.');
  abbreviationMapping.set('pref.', 'preface.');
  abbreviationMapping.set('prep., prepp.', 'preposition, prepositions.');
  abbreviationMapping.set('pres.', 'present.');
  abbreviationMapping.set('pret.', 'preterite.');
  abbreviationMapping.set('priv.', 'privative.');
  abbreviationMapping.set('pr. n.', 'proper name.');
  abbreviationMapping.set('prob.', 'probably.');
  abbreviationMapping.set('pron.', 'pronoun.');
  abbreviationMapping.set('proncd.', 'pronounced.');
  abbreviationMapping.set('proverb.', 'proverbially.');
  abbreviationMapping.set('provinc.', 'provincial.');
  abbreviationMapping.set('qs.', 'quasi.');
  abbreviationMapping.set('q. v.', 'quod vide.');
  abbreviationMapping.set('R.', 'Rimur.');
  abbreviationMapping.set('recipr.', 'reciprocally.');
  abbreviationMapping.set('redupl.', 'reduplicative.');
  abbreviationMapping.set('reflex.', 'retlexive.');
  abbreviationMapping.set('relat.', 'relative.');
  abbreviationMapping.set('S.', 'Saga.');
  abbreviationMapping.set('s. a.', 'sub anno.');
  abbreviationMapping.set('Sansk.', 'Sanskrit.');
  abbreviationMapping.set('Scandin.', 'Scandinavia, Scandinavian.');
  abbreviationMapping.set('Scot.', 'Scottish.');
  abbreviationMapping.set('signif.', 'signification.');
  abbreviationMapping.set('sing.', 'singular.');
  abbreviationMapping.set('Slav.', 'Slavonic.');
  abbreviationMapping.set('Span.', 'Spanish.');
  abbreviationMapping.set('spec.', 'specially.');
  abbreviationMapping.set('sq., sqq.', 'following.');
  abbreviationMapping.set('subj.', 'subjunctive.');
  abbreviationMapping.set('subst.', 'substantive.');
  abbreviationMapping.set('uff.', 'suffix.');
  abbreviationMapping.set('sup.', 'supine.');
  abbreviationMapping.set('superl.', 'superlative.');
  abbreviationMapping.set('s. v.', 'sub voce.');
  abbreviationMapping.set('Swed.', 'Swedish.');
  abbreviationMapping.set('temp.', 'temporal.');
  abbreviationMapping.set('termin.', 'termination.');
  abbreviationMapping.set('Teut.', 'Teutonic.');
  abbreviationMapping.set('theol.', 'theological, theologically.');
  abbreviationMapping.set('trans.', 'transitive.');
  abbreviationMapping.set('transl.', 'translation.');
  abbreviationMapping.set('trisyl.', 'trisyllabic.');
  abbreviationMapping.set('Ulf.', 'Ulfilas.');
  abbreviationMapping.set('uncert.', 'uncertain.');
  abbreviationMapping.set('unclass.', 'unclassical.');
  abbreviationMapping.set('Ups. De la Gard.', 'De la Garde’s collection of Icel. MSS. in Upsala.');
  abbreviationMapping.set('v.', 'vide.');
  abbreviationMapping.set('viz.', 'namely.');
  abbreviationMapping.set('v. l.', 'varia lectio.');
  abbreviationMapping.set('Wolf.', 'Wolfenbüttel.');
  abbreviationMapping.set('þ.', 'þáttr.');

  return abbreviationMapping;
};

export default {
  getAbbreviationMapping,
};
