export const getWorksAndAuthorsMapping = (): Map<string, string> => {
  const worksAndAuthorsMapping = new Map();
  worksAndAuthorsMapping.set('A. A.', 'Antiquitates Americanae. (E. II.)');
  worksAndAuthorsMapping.set('Ad.', 'Arinbjarnar-drápa. (A. III.)');
  worksAndAuthorsMapping.set('Akv.', 'Atla-kviða. (A. II.)');
  worksAndAuthorsMapping.set('Al.', 'Alexanders Saga. (G. I.)');
  worksAndAuthorsMapping.set('Alg.', 'Algorismus. (H. III.)');
  worksAndAuthorsMapping.set('Alm.', 'Alvís-mál. (A. I.)');
  worksAndAuthorsMapping.set('Am.', 'Atla-mál. (A. II.)');
  worksAndAuthorsMapping.set('Anal.', 'Analecta. (D. II.)');
  worksAndAuthorsMapping.set('Andr.', 'Andreas Saga. (F. III.)');
  worksAndAuthorsMapping.set('Anecd.', 'Anecdoton. (H. II.)');
  worksAndAuthorsMapping.set('Ann.', 'Íslenzkir Annálar. (D. IV.)');
  worksAndAuthorsMapping.set('Ant. S.', 'Antonius Saga. (F. III.)');
  worksAndAuthorsMapping.set('Arna-Magn. or A. M.', 'Arna-Magnacanus.');
  worksAndAuthorsMapping.set('Arons S.', 'Arons Saga. (D. III.)');
  worksAndAuthorsMapping.set('Art.', 'Artus-kappa Sögur. (G. II.)');
  worksAndAuthorsMapping.set('Aug.', 'Augustinus Saga. (F. III.)');
  worksAndAuthorsMapping.set('A. þ.', 'Arfa-þáttr. (B. I.)');
  worksAndAuthorsMapping.set('Ágr.', 'Ágrip. (E. I.)');
  worksAndAuthorsMapping.set('Ám.', 'Auðunnar-máldagi. (J. I.)');
  worksAndAuthorsMapping.set('Árna S.', 'Árna Saga. (D. III.)');
  worksAndAuthorsMapping.set('Band.', 'Banda-manna Saga. (D. II.)');
  worksAndAuthorsMapping.set('Barl.', 'Barlaams Saga. (F. III.)');
  worksAndAuthorsMapping.set('Baut.', 'Bautil. (K. II.)');
  worksAndAuthorsMapping.set('Bárð.', 'Bárðar Saga. (D. V.)');
  worksAndAuthorsMapping.set('Bb.', 'Búnaðar-bálkr.');
  worksAndAuthorsMapping.set('Bev.', 'Bevus Saga. (G. II.)');
  worksAndAuthorsMapping.set('Bjarn.', 'Bjarnar Saga. (D. II.)');
  worksAndAuthorsMapping.set('Bjarni', 'Bjarni Thorarinson.');
  worksAndAuthorsMapping.set('Björn', 'Biörn Halldórsson.');
  worksAndAuthorsMapping.set('B. K.', 'Björgynjar Kálfskinn. (J. II.)');
  worksAndAuthorsMapping.set('Bkv.', 'Brynhildar-kviða. (A. II.)');
  worksAndAuthorsMapping.set('Blas.', 'Blasius Saga. (F. III.)');
  worksAndAuthorsMapping.set('Bm.', 'Bjarka-mál. (A. II.)');
  worksAndAuthorsMapping.set('Boldt', 'Boldt. (J. II.)');
  worksAndAuthorsMapping.set('Boll.', 'Bolla-þáttr. (D. V.)');
  worksAndAuthorsMapping.set('Brandkr.', 'Brandkrossa-þáttr. (D. V.)');
  worksAndAuthorsMapping.set('Bret.', 'Breta Sögur. (G. I.)');
  worksAndAuthorsMapping.set('Brocm.', 'Brocman. (K. II.)');
  worksAndAuthorsMapping.set('Bs.', 'Biskupa Sögur. (D. III.)');
  worksAndAuthorsMapping.set('Bt.', 'Bauga-tal. (B. I.)');
  worksAndAuthorsMapping.set('Bær.', 'Bærings Saga. (G. II.)');
  worksAndAuthorsMapping.set('Clar.', 'Clarus Saga. (G. II.)');
  worksAndAuthorsMapping.set('Clem.', 'Clements Saga. (F. III.)');
  worksAndAuthorsMapping.set('Darr.', 'Darraðar-ljóð. (A. III.)');
  worksAndAuthorsMapping.set('D. I.', 'Diplomatarium Islandicum. (J. I.)');
  worksAndAuthorsMapping.set('Dipl.', 'Diplomatarium. (J. I.)');
  worksAndAuthorsMapping.set('D. N.', 'Diplomatarium Norvagicum. (J. II.)');
  worksAndAuthorsMapping.set('Dropl.', 'Droplaugar-sona Saga. (D. II.)');
  worksAndAuthorsMapping.set('Eb.', 'Eyrbyggja Saga. (D. II.)');
  worksAndAuthorsMapping.set('Edda', 'Edda. (C. I.)');
  worksAndAuthorsMapping.set('Eg.', 'Egils Saga. (D. II.)');
  worksAndAuthorsMapping.set('El.', 'Elis Saga. (G. II.)');
  worksAndAuthorsMapping.set('Eluc.', 'Elucidarium. (F. II.)');
  worksAndAuthorsMapping.set('Em.', 'Eiríks-mál. (A. III.)');
  worksAndAuthorsMapping.set('Esp.', 'Espólin Árbækr Íslands.');
  worksAndAuthorsMapping.set('Fagrsk.', 'Fagrskinna. (K. I.)');
  worksAndAuthorsMapping.set('Fas.', 'Fornaldar Sögur. (C. II.)');
  worksAndAuthorsMapping.set('Fb.', 'Flateyjar-bók (E. I.)');
  worksAndAuthorsMapping.set('Fbr.', 'Fóstbræðra Saga. (D. II.)');
  worksAndAuthorsMapping.set('Fél.', 'Félags-rit.');
  worksAndAuthorsMapping.set('Finnb.', 'Finnboga Saga. (D. V.)');
  worksAndAuthorsMapping.set('Fkv.', 'Forn-kvæði.');
  worksAndAuthorsMapping.set('Flóam. S.', 'Flóamanna Saga. (E. I.)');
  worksAndAuthorsMapping.set('Flóv.', 'Flóvents Saga. (G. II.)');
  worksAndAuthorsMapping.set('Fm.', 'Fafnis-mál. (A. II.)');
  worksAndAuthorsMapping.set('Fms.', 'Fornmanna Sögur. (E. I.)');
  worksAndAuthorsMapping.set('Fr.', 'Fritzner’s Dictionary, 1867.');
  worksAndAuthorsMapping.set('Frump.', 'Frumpartar.');
  worksAndAuthorsMapping.set('Fs.', 'Forn-sögur. (D. II.)');
  worksAndAuthorsMapping.set('Fsm.', 'Fjölsvinns-mál. (A. II.)');
  worksAndAuthorsMapping.set('Fspl.', 'Forspjalls-ljóð. (A. I.)');
  worksAndAuthorsMapping.set('F. þ.', 'Festa-þáttr. (B. I.)');
  worksAndAuthorsMapping.set('Fær.', 'Færeyinga Saga. (E. II.)');
  worksAndAuthorsMapping.set('Gautr.', 'Gautreks Saga. (C. II.)');
  worksAndAuthorsMapping.set('Gg.', 'Grógaldr. (A. II.)');
  worksAndAuthorsMapping.set('Gh.', 'Guðrúnar-hefna. (A. II.)');
  worksAndAuthorsMapping.set('Gísl.', 'Gísla Saga. (D. II.)');
  worksAndAuthorsMapping.set('Gkv.', 'Guðrúnar-kviða. (A. II.)');
  worksAndAuthorsMapping.set('Glúm.', 'Víga-Glúms Saga. (D. II.)');
  worksAndAuthorsMapping.set('Gm.', 'Grímnis-mál. (A. I.)');
  worksAndAuthorsMapping.set('Grág.', 'Grágás. (B. I.)');
  worksAndAuthorsMapping.set('Greg.', 'Gregory. (F. II.)');
  worksAndAuthorsMapping.set('Grett.', 'Grettis Saga. (D. II.)');
  worksAndAuthorsMapping.set('Grönd.', 'Benedikt Gröndal.');
  worksAndAuthorsMapping.set('Grönl. Hist. Mind.', 'Grönlands Historiske Mindes-mærker.');
  worksAndAuthorsMapping.set('Gs.', 'Grótta-söngr. (A. II.)');
  worksAndAuthorsMapping.set('Gsp.', 'Getspeki Heiðreks. (A. II.)');
  worksAndAuthorsMapping.set('Guðm. S.', 'Guðmundar Saga. (D. III.)');
  worksAndAuthorsMapping.set('Gullþ.', 'Gull-Þóris Saga. (D. II.)');
  worksAndAuthorsMapping.set('Gylfag.', 'Gylfa-ginning. (C. I.)');
  worksAndAuthorsMapping.set('Gþl.', 'Gulaþings-lög. (B. II.)');
  worksAndAuthorsMapping.set('Hallfr. S.', 'Hallfreðar Saga. (D. II.)');
  worksAndAuthorsMapping.set('Hallgr.', 'Hallgrímr Pétrsson.');
  worksAndAuthorsMapping.set('H. Ann.', 'Hauks-annáll. (D. IV.)');
  worksAndAuthorsMapping.set('Harð. S.', 'Harðar Saga. (D. II.)');
  worksAndAuthorsMapping.set('Har. S. Harð.', 'Haralds Saga Harðráða. (E. I.)');
  worksAndAuthorsMapping.set('Haustl.', 'Haustlöng. (A. I.)');
  worksAndAuthorsMapping.set('Hák. S.', 'Hákonar Saga. (E. I.)');
  worksAndAuthorsMapping.set('Hálfs S.', 'Hálfs Saga. (C. II.)');
  worksAndAuthorsMapping.set('Háv.', 'Hávarðar Saga. (D. II.)');
  worksAndAuthorsMapping.set('Hb.', 'Hauks-bók. (H. IV.)');
  worksAndAuthorsMapping.set('Hbl.', 'Harbarðs-ljóð. (A. I.)');
  worksAndAuthorsMapping.set('Hd.', 'Hús-drápa. (A. I.)');
  worksAndAuthorsMapping.set('Hdl.', 'Hyndlu-ljóð. (A. II.)');
  worksAndAuthorsMapping.set('Hðm.', 'Hamðis-mál. (A. II.)');
  worksAndAuthorsMapping.set('H. E.', 'Historia Ecclesiastica Islandiae. (J. I.)');
  worksAndAuthorsMapping.set('Heiðarv. S. or Heið. S.', 'Heiðarvíga Saga. (D. II.)');
  worksAndAuthorsMapping.set('Helr.', 'Helreið Brynhildar. (A. II.)');
  worksAndAuthorsMapping.set('Hem.', 'Hemings-þáttr. (C. H.)');
  worksAndAuthorsMapping.set('Hervar. S.', 'Hervarar Saga. (C. II.)');
  worksAndAuthorsMapping.set('Hjalt.', 'Hjaltalín, Icelandic Botany.');
  worksAndAuthorsMapping.set('Hkm.', 'Hákonar-mál. (A. III.)');
  worksAndAuthorsMapping.set('Hkr.', 'Heimskringla. (E. I.)');
  worksAndAuthorsMapping.set('Hkv.', 'Helga-kviða Hundingsbana. (A. II.)');
  worksAndAuthorsMapping.set('Hkv. Hjörv.', 'Helga-kviða Hjörvarðssonar. (A. II.)');
  worksAndAuthorsMapping.set('Hlt.', 'Háleygja-tal. (A. II.)');
  worksAndAuthorsMapping.set('Hm.', 'Hává-mál. (A. I.)');
  worksAndAuthorsMapping.set('Hom.', 'Homiliu-bók. (F. II.)');
  worksAndAuthorsMapping.set('Hrafn.', 'Hrafnkels Saga. (D. II.)');
  worksAndAuthorsMapping.set('Hrólfs Kr. S.', 'Hrólfs Saga Kraka.(C. II.)');
  worksAndAuthorsMapping.set('Hs.', 'Harm-sol. (A. III.)');
  worksAndAuthorsMapping.set('Hsm.', 'Hugsvinns-mál. (A. III.)');
  worksAndAuthorsMapping.set('Ht.', 'Hátta-tal. (C. I.)');
  worksAndAuthorsMapping.set('Hung. or Hv.', 'Hungr-vaka. (D. III)');
  worksAndAuthorsMapping.set('Húst.', 'Hús-tafla.');
  worksAndAuthorsMapping.set('Hým.', 'Hýmis-kviða. (A. I.)');
  worksAndAuthorsMapping.set('Hænsaþ.', 'Hænsa-Þóris Saga. (D. II.)');
  worksAndAuthorsMapping.set('Höfuðl.', 'Höfuðlausn. (A. III.)');
  worksAndAuthorsMapping.set('Itin.', 'Itinerarium or Travels of Eggert Ólafsson, 1772.');
  worksAndAuthorsMapping.set('Ivar Aasen', 'Ivar Aasen’s Dictionary, 1850.');
  worksAndAuthorsMapping.set('Íb.', 'Íslendinga-bók. (D. I.)');
  worksAndAuthorsMapping.set('Íd.', 'Íslendinga-drápa. (A. III.)');
  worksAndAuthorsMapping.set('Ingv.', 'Ingvars Saga. (E. I.)');
  worksAndAuthorsMapping.set('Ísl. Þjóðs.', 'Íslenzkar Þjóðsögur.');
  worksAndAuthorsMapping.set('Játv.', 'Játvarðar Saga. (E. II.)');
  worksAndAuthorsMapping.set('Jb.', 'Jóns-bók. (B. III.)');
  worksAndAuthorsMapping.set('Jd.', 'Jómsvíkinga-drápa. (A. III.)');
  worksAndAuthorsMapping.set('Jm.', 'Jóns-máldagi. (J. I.)');
  worksAndAuthorsMapping.set('Jóh.', 'Jóhannes Saga. (F. III.)');
  worksAndAuthorsMapping.set('Jómsv. S. or Jv.', 'Jómsvíkinga Saga. (E. I.)');
  worksAndAuthorsMapping.set('Jónas', 'Jónas Hallgrímsson.');
  worksAndAuthorsMapping.set('Jóns S.', 'Jóns Saga. (D. III.)');
  worksAndAuthorsMapping.set('Jón Þorl.', 'Jón Þorláksson.');
  worksAndAuthorsMapping.set('Js.', 'Járnsíða. (B. III.)');
  worksAndAuthorsMapping.set('Karl.', 'Karla-magnús Saga. (G. I.)');
  worksAndAuthorsMapping.set('K. Á.', 'Kristinn-réttr Árna biskups. (B. III.)');
  worksAndAuthorsMapping.set('Kb.', 'Konungs-bók. (B. I, C. I, etc.)');
  worksAndAuthorsMapping.set('Kjaln. S.', 'Kjalnesinga Saga. (D. V.)');
  worksAndAuthorsMapping.set('Km.', 'Kráku-mál. (A. III.)');
  worksAndAuthorsMapping.set('Knytl.', 'Knytlinga Saga. (E. I.)');
  worksAndAuthorsMapping.set('Konr.', 'Konráðs Saga. (G. III.)');
  worksAndAuthorsMapping.set('Korm.', 'Kormaks Saga. (D. II.)');
  worksAndAuthorsMapping.set('Kristni S. or Kr. S.', 'Kristni Saga. (D. I. III.)');
  worksAndAuthorsMapping.set('Krók.', 'Króka Refs Saga. (D. V.)');
  worksAndAuthorsMapping.set('K. Þ. K.', 'Kristinn-réttr Þorláks ok Ketils = Kristinna-laga-þáttr. (B. I.)');
  worksAndAuthorsMapping.set('Landn.', 'Landnáma. (D. I.)');
  worksAndAuthorsMapping.set('Laur. S.', 'Laurentius Saga. (D. III.)');
  worksAndAuthorsMapping.set('Ld.', 'Laxdæla Saga. (D. II.)');
  worksAndAuthorsMapping.set('Lex. Mythol.', 'Lexicon Mythologicum.');
  worksAndAuthorsMapping.set('Lex. Poët.', 'Lexicon Poëticum by Sveinbjörn Egilsson, 1860.');
  worksAndAuthorsMapping.set('Lex. Run.', 'Lexicon Runicum.');
  worksAndAuthorsMapping.set('Lil.', 'Lilja. (A. III.)');
  worksAndAuthorsMapping.set('Ls.', 'Loka-senna. (A. I.)');
  worksAndAuthorsMapping.set('Lv.', 'Ljósvetninga Saga. (D. II.)');
  worksAndAuthorsMapping.set('Lækn.', 'Lækninga-bók. (H. V.)');
  worksAndAuthorsMapping.set('Mag.', 'Magus Saga. (G. II.)');
  worksAndAuthorsMapping.set('Magn.', 'Magnús Saga jarls. (E. II.)');
  worksAndAuthorsMapping.set('Magn. S. Góða', 'Magnús Saga Góða. (E. I.)');
  worksAndAuthorsMapping.set('Mar.', 'Maríu Saga. (F. III.)');
  worksAndAuthorsMapping.set('Mart.', 'Martinus Saga. (F. III.)');
  worksAndAuthorsMapping.set('Merl.', 'Merlinus Spa. (A. III.)');
  worksAndAuthorsMapping.set('Mirm.', 'Mirmants Saga. (G. II.)');
  worksAndAuthorsMapping.set('M. K.', 'Munkalíf. (J. II.)');
  worksAndAuthorsMapping.set('Mkv.', 'Málshátta-kvæði. (A. III.)');
  worksAndAuthorsMapping.set('Mork.', 'Morkinskinna. (E. I.)');
  worksAndAuthorsMapping.set('Mött.', 'Möttuls Saga. (G. I.)');
  worksAndAuthorsMapping.set('N. G. L.', 'Norges Gamle Love. (B. II.)');
  worksAndAuthorsMapping.set('Niðrst.', 'Niðrstigningar Saga. (F. III.)');
  worksAndAuthorsMapping.set('Nj.', 'Njála. (D. II.)');
  worksAndAuthorsMapping.set('Njarð.', 'Njarðvíkinga Saga. (D. II.)');
  worksAndAuthorsMapping.set('Njóla', 'Njóla, the poem.');
  worksAndAuthorsMapping.set('Norge’s Beskriv.', 'Beskrivelse Norge.');
  worksAndAuthorsMapping.set('Norna G. S.', 'Norna-Gests Saga. (C. II.)');
  worksAndAuthorsMapping.set('N. T.', 'New Testament.');
  worksAndAuthorsMapping.set('Ný Fél.', 'Ný Félags-rit.');
  worksAndAuthorsMapping.set('Ob.', 'Orms-bók. (C. I.)');
  worksAndAuthorsMapping.set('Od.', 'Odysseifs-kvæði, prose, 1829.');
  worksAndAuthorsMapping.set('Odd. or S. Odd.', 'Stjörnu-Odda draumr. (D. V.)');
  worksAndAuthorsMapping.set('Og.', 'Oddrúnar-grátr. (A. II.)');
  worksAndAuthorsMapping.set('O. H. L.', 'Ólafs Saga Helga Legendaria. (E. I.)');
  worksAndAuthorsMapping.set('Ór.', 'Ólafs-ríma. (A. III)');
  worksAndAuthorsMapping.set('Orkn.', 'Orkneyinga Saga. (E. II.)');
  worksAndAuthorsMapping.set('Ób.', 'Ómaga-bálkr. (B. I.)');
  worksAndAuthorsMapping.set('Ó. H.', 'Ólafs Saga Helga. (E. I.)');
  worksAndAuthorsMapping.set('Ósv.', 'Ósvalds Saga. (K. II.)');
  worksAndAuthorsMapping.set('Ó. T.', 'Ólafs Saga Tryggvasonar. (E. I.)');
  worksAndAuthorsMapping.set('Pass.', 'Passiu-Sálmar.');
  worksAndAuthorsMapping.set('Páls S.', 'Páls Saga. (D. III.)');
  worksAndAuthorsMapping.set('Pd.', 'Placidus-drápa. (A. III.)');
  worksAndAuthorsMapping.set('Pm.', 'Pétrs-máldagi. (J. I.)');
  worksAndAuthorsMapping.set('Post.', 'Postula Sögur. (F. III.)');
  worksAndAuthorsMapping.set('Rafns. S.', 'Rafns Saga. (D. III.)');
  worksAndAuthorsMapping.set('Ragn. S.', 'Ragnars Saga. (C. II.)');
  worksAndAuthorsMapping.set('Rb.', 'Rímbegla. (H. III.)');
  worksAndAuthorsMapping.set('Rd.', 'Reykdæla Saga. (D. II.)');
  worksAndAuthorsMapping.set('Rétt.', 'Réttarbætr. (B. II.)');
  worksAndAuthorsMapping.set('Rm.', 'Rígsmál. (A. II.)');
  worksAndAuthorsMapping.set('Róm.', 'Rómverja Saga. (E. II.)');
  worksAndAuthorsMapping.set('Safn', 'Safn til Sögu Islands.');
  worksAndAuthorsMapping.set('Sb.', 'Staðarhóls-bók. (B. I.)');
  worksAndAuthorsMapping.set('Sd.', 'Svarfdæla Saga. (D. II.)');
  worksAndAuthorsMapping.set('Sdm.', 'Sigrdrífu-mál. (A. II.)');
  worksAndAuthorsMapping.set('Sig. Breiðf.', 'Sigurðr Breiðfjörð.');
  worksAndAuthorsMapping.set('Sig. Pét.', 'Sigurðr Pétrsson.');
  worksAndAuthorsMapping.set('Skálda', 'Skálda. (H. I.)');
  worksAndAuthorsMapping.set('Skáld H.', 'Skáld Helga-rímur. (A. III.)');
  worksAndAuthorsMapping.set('Skjöld.', 'Skjöldunga Saga. (C. II.)');
  worksAndAuthorsMapping.set('Skm.', 'Skírnis-mál. (A. I.)');
  worksAndAuthorsMapping.set('Sks.', 'Konungs Skugg-sjá. (H. II.)');
  worksAndAuthorsMapping.set('Sksm.', 'Skáldskapar-mál. (C. I.)');
  worksAndAuthorsMapping.set('Skv.', 'Sigurðar-kviða. (A. II.)');
  worksAndAuthorsMapping.set('Sl. or Sól.', 'Sólarljóð. (A. III.)');
  worksAndAuthorsMapping.set('Snót', 'Snót, poems.');
  worksAndAuthorsMapping.set('Stef. Ól.', 'Stefán Ólafsson.');
  worksAndAuthorsMapping.set('Stell.', 'Stellu-rímur.');
  worksAndAuthorsMapping.set('Stj.', 'Stjórn. (F. I.)');
  worksAndAuthorsMapping.set('Stor.', 'Sona-torrek. (A. III.)');
  worksAndAuthorsMapping.set('Str.', 'Strengleikar. (G. II.)');
  worksAndAuthorsMapping.set('Sturl.', 'Sturlunga Saga. (D. I.)');
  worksAndAuthorsMapping.set('Sverr. S.', 'Sverris Saga. (E. I.)');
  worksAndAuthorsMapping.set('Symb.', 'Symbolae. (H. IV.)');
  worksAndAuthorsMapping.set('Sæm.', 'Sæmundar Edda. (A, C. I.)');
  worksAndAuthorsMapping.set('Th.', 'Theophilus. (F. III.)');
  worksAndAuthorsMapping.set('Thorn.', 'Thomas Saga. (E. II.)');
  worksAndAuthorsMapping.set('Tl.', 'Tíundar-lög. (B. I.)');
  worksAndAuthorsMapping.set('Tristr.', 'Tristrams Saga. (G. II.)');
  worksAndAuthorsMapping.set('Ub.', 'Uppsala-bók. (C. I.)');
  worksAndAuthorsMapping.set('Úlf.', 'Úlfars-rímur.');
  worksAndAuthorsMapping.set('Valla L.', 'Valla Ljóts Saga. (D. II.)');
  worksAndAuthorsMapping.set('Vápn.', 'Vápnfirðinga Saga. (D. II.)');
  worksAndAuthorsMapping.set('Vd.', 'Vatnsdæla Saga. (D. II.)');
  worksAndAuthorsMapping.set('Ver.', 'Veraldar Saga. (E. II.)');
  worksAndAuthorsMapping.set('Verel.', 'Verelius, Index.');
  worksAndAuthorsMapping.set('Vh.', 'Vatnshyrna MS.');
  worksAndAuthorsMapping.set('Vídal.', 'Vídalíns-Postilla.');
  worksAndAuthorsMapping.set('Vídal. Skýr.', 'Vídalín Skýringar.');
  worksAndAuthorsMapping.set('Vígl.', 'Víglundar Saga. (D. V.)');
  worksAndAuthorsMapping.set('Vínl. þ.', 'Vínlands-þáttr. (E. II.)');
  worksAndAuthorsMapping.set('Vkv.', 'Völundar-kviða. (A. II.)');
  worksAndAuthorsMapping.set('Vm.', 'Vilkins-máldagi. (J. I.)');
  worksAndAuthorsMapping.set('Vsl.', 'Vígslóði. (B. I.)');
  worksAndAuthorsMapping.set('Vsp.', 'Völuspá. (A. I.)');
  worksAndAuthorsMapping.set('Vtkv.', 'Vegtams-kviða. (A. I.)');
  worksAndAuthorsMapping.set('Vþm.', 'Vafþrúðnis-mál. (A. I.)');
  worksAndAuthorsMapping.set('Völs. S.', 'Völsunga Saga. (C. II.)');
  worksAndAuthorsMapping.set('Yngl. S.', 'Ynglinga Saga. (C. II.)');
  worksAndAuthorsMapping.set('Yt.', 'Ynglinga-tal. (A. II.)');
  worksAndAuthorsMapping.set('Þd.', 'Þórs-drápa. (A. I.)');
  worksAndAuthorsMapping.set('Þiðr.', 'Þiðreks Saga. (G. I.)');
  worksAndAuthorsMapping.set('Þjal.', 'Þjalar-Jóns Saga. (G. III.)');
  worksAndAuthorsMapping.set('Þkv.', 'Þryms-kviða. (A. I.)');
  worksAndAuthorsMapping.set('Þorf. Karl.', 'Þorfinns Saga Karlsefnis. (D. II.)');
  worksAndAuthorsMapping.set('Þorl. S.', 'Þorláks Saga. (D. III.)');
  worksAndAuthorsMapping.set('Þorst. hv.', 'Þorsteins-þáttr hvíta. (D. II.)');
  worksAndAuthorsMapping.set('Þorst. Síðu H.', 'Þorsteins Saga Síðu-Hallssonar. (D. II.)');
  worksAndAuthorsMapping.set('Þorst. S. St.', 'Þorsteins-þáttr Stangarhöggs. (D. II.)');
  worksAndAuthorsMapping.set('Þorst. ux.', 'Þorsteins-þattr uxafóts. (D. V.)');
  worksAndAuthorsMapping.set('Þórð.', 'Þórðar Saga hreðu. (D. V.)');
  worksAndAuthorsMapping.set('Þ. þ.', 'Þingskapa-þáttr. (B. I.)');
  worksAndAuthorsMapping.set('Ölk.', 'Ölkofra-þáttr. (D. II.)');

  return worksAndAuthorsMapping;
};

export default {
  getWorksAndAuthorsMapping,
};
